import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";

// Precache the files generated by the build process
/* eslint-disable-next-line no-restricted-globals */
precacheAndRoute(self.__WB_MANIFEST);

// Use a stale-while-revalidate strategy for all other requests
registerRoute(
  ({ request }) => request.destination === "image",
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [
      // Add plugins if necessary
    ],
  })
);

// Listen to 'install' event
/* eslint-disable-next-line no-restricted-globals */
self.addEventListener("install", (event) => {
  console.log("Service Worker installing.");
});

// Listen to 'activate' event
/* eslint-disable-next-line no-restricted-globals */
self.addEventListener("activate", (event) => {
  console.log("Service Worker activating.");
});
