import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

// Precache the files generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Use a stale-while-revalidate strategy for all other requests
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Add plugins if necessary
    ],
  })
);

// Listen to 'install' event
self.addEventListener('install', (event) => {
  console.log('Service Worker installing.');
});

// Listen to 'activate' event
self.addEventListener('activate', (event) => {
  console.log('Service Worker activating.');
});
